### ISSUE TITLE
Patched apk failure of mounting 

### ISSUE THREAD

**Issue by kaiminz** [inotia00/rvx-builder#101]
**Describe the bug**
Patched apk cannot be mounted 

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [Android 9]
- Device: [OnePlus 6]

**Additional context**

**Comment by inotia00** [comment]
Please upload a screenshot of the issue you are experiencing

**Comment by kaiminz** [comment]
There are no mounting sh documents in /data/adb/service.d and post-fs-data.d. Patched YouTube is the same as original one，nothing happens.

**Comment by kaiminz** [comment]
And in adb/revanced Archive there exists the patched apk. In rvx patching process, it shows it is patched and installed successfully. Android rooted phone, termux tool.

**Comment by inotia00** [comment]
did you followed this steps?
https://github.com/inotia00/revanced-documentation/wiki/Before-start-(Prerequisites)#common

**Comment by kaiminz** [comment]
Yes, Sir. I'm familiar with the process, and in termux I use Revancify before. But Revancify stopped yesterday, so I use your rvx Android builder in termux, and it fails in mounting (no problem in patching and patched apk
). 
Fortunately your rvx-manager can do it well.

**Comment by kaiminz** [comment]
For YT 18.27.36

**Comment by inotia00** [comment]
This seems to be the important information for the issue
I'll test it later

**Comment by kaiminz** [comment]
Many thanks for your patience and dedications in the brilliant job!

**Comment by kaiminz** [comment]
![Screenshot_20230729-204251](https://github.com/inotia00/rvx-builder/assets/89754237/fdb319fd-b4c4-40e4-8bf7-e9e227affe17)
![Screenshot_20230729-204452](https://github.com/inotia00/rvx-builder/assets/89754237/886e0cdf-5fe5-4a21-a682-bae07bada86f)
![Screenshot_20230729-204534](https://github.com/inotia00/rvx-builder/assets/89754237/27454dff-74a0-4c48-8139-ec626039669e)

**Comment by kaiminz** [comment]
Once again, uninstall revanced yt, cancel docs in the data/adb/service.d, post-fs-data.d, and revanced. Reboot phone, install YT, patching...., finally it seems nothing happens to YT. No restart page, too.

**Comment by inotia00** [comment]
fixed in [rvx-builder-v3.9.15](https://github.com/inotia00/rvx-builder/releases/tag/v3.9.15)
