### ISSUE TITLE
ReVanced Builder 3.9.6 fails under macOS

### ISSUE THREAD

**Issue by mavethee** [inotia00/rvx-builder#103]
**Describe the bug**
Cannot patch any app.

**To Reproduce**

1. Run the script on macOS
2. Press start
3. Error pops up

**Screenshots**

![CleanShot 2023-07-29 at 21 12 53@2x](https://github.com/inotia00/rvx-builder/assets/47083527/5a931fa3-21bd-477b-814d-9ec1d5f28c89)

**revanced-builder Version:** 3.9.6
**Desktop (please complete the following information):**

- OS: macOS
- Version: 14 Beta 4

**Additional context**

**Comment by inotia00** [comment]
delete `settings.json` files where rvx-builder located
