### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Mogez** [inotia00/rvx-builder#105]
**Describe the bug**
Click Start patching, and stopped with red errors messages.

**Screenshots**
![2023-07-31_214057](https://github.com/inotia00/rvx-builder/assets/30268631/46f2f683-582e-4606-8d20-1cfd5ac1c344)
![2023-07-31_214251](https://github.com/inotia00/rvx-builder/assets/30268631/40bf1959-cdc6-4148-acd3-f49d5c2f49ad)

**revanced-builder Version:** [e.g. v1.2.10]
v3.9.6

**Desktop (please complete the following information):**
OS	Windows 10 Version 21H2 (Build 19044.3208)
Vivaldi	5.6.2867.50 (Stable channel) (64-bit) 
JavaScript	V8 10.8.168.22

**Comment by inotia00** [comment]
Windows, Mac, Linux
==
delete `settings.json` files where rvx-builder located

Termux (Android)
==
just reinstall

type:
```
./rvx-builder.sh reinstall && ./rvx-builder.sh run
```
