### ISSUE TITLE
Patching is stuck when using official repositories

### ISSUE THREAD

**Issue by auanasgheps** [inotia00/rvx-builder#107]
**Describe the bug**
Patching does not go beyond initial stage when using official repositories

**To Reproduce**

1. Configure `revanced` for each Organization
2. Save
3. Try to patch an app like YouTube
4. It will get stuck

**Screenshots**
![image](https://github.com/inotia00/rvx-builder/assets/20586878/ae237293-363f-4024-a4a9-6c71b440bed7)

![image](https://github.com/inotia00/rvx-builder/assets/20586878/39750827-5ec1-4a08-8c93-2d135ec14ae4)

**revanced-builder Version:** 3.9.1.0

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**
N/A

**Comment by inotia00** [comment]
It only supports my CLI
There are plans for future support, but not right now

**Comment by auanasgheps** [comment]
ok thank you.

**Comment by inotia00** [comment]
`rvx-builder v3.9.12` is now compatible with the official revanced-cli

To patch with official revanced sources, change `RipLibs` to off

**Comment by auanasgheps** [comment]
THANK YOU! It works! And I was able to carry my keystore key from the original Revanced Builder!
