### ISSUE TITLE
How to provide a Reddit Client ID?

### ISSUE THREAD

**Issue by auanasgheps** [inotia00/rvx-builder#108]
**Describe the bug**
How do I provide a Reddit Client ID to build a modded Reddit Client?

On Android I would create `reddit_client_id_revanced.tx`t in the storage root containing the Reddit ID.
I tried placing such file in the `revanced` folder, but I get this error:

`GRAVE: Spoof client failed: app.revanced.patcher.patch.PatchException: No client ID provided`

**To Reproduce**

1. Attempt to build a Reddit client such as Infinity or Sync for Reddit
2. Enable mod _Spoof Client_
3. Build will fail because the Client ID is missing

**Screenshots**
![immagine](https://github.com/inotia00/rvx-builder/assets/20586878/4987b791-ae06-4846-ab64-c18d5a291986)

![immagine](https://github.com/inotia00/rvx-builder/assets/20586878/92cff125-8993-4db3-a401-0e97804ed146)

**revanced-builder Version:** 3.9.12

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**
Using Official Revanced patches

**Comment by inotia00** [comment]
rvx-builder is compatible with official ReVanced sources, but this does not mean it provides support for official ReVanced Patches

Ask the official [ReVanced subreddit](https://www.reddit.com/r/revancedapp/comments/15326az/continue_using_your_favorite_thirdparty_reddit/)

btw rvx-builder is patched with CLI, so you need to add the value to `options.json`

**Comment by auanasgheps** [comment]
Thanks, it works :)
