### ISSUE TITLE
Immediate bug when starting the builder

### ISSUE THREAD

**Issue by SamuelSHrk** [inotia00/rvx-builder#110]
**Describe the bug**
Bug regarding JSON tokens or something
**To Reproduce**

1. Go to RVX Builder
3. Click on Start Patching
4. Wait for it to download dependencies then continue
5. See error

**revanced-builder Version: 3.9.12** 

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

![image](https://github.com/inotia00/rvx-builder/assets/43790833/a335b6c7-de46-4a2f-a9f3-8e17034dcb62)

**Comment by Shaarigan** [comment]
There may be different reasons for this to fail. Either you have somehow APKMirror being blocked by whatever reasons for you or the API is down at the moment. However, use [this v3.9.12-1](https://github.com/Shaarigan/rvx-builder/releases/tag/v3.9.12) until @inotia00 makes a new release with my workaround applied.

I have the problem that APKMirror is sometimes blocked depending on the network I use and this one works for me. But keep in mind you'll need to provide a downloaded APK if fetching fails

**Comment by inotia00** [comment]
fixed in [rvx-builder-v3.9.15](https://github.com/inotia00/rvx-builder/releases/tag/v3.9.15)
