### ISSUE TITLE
Custom Package Name option makes java error

### ISSUE THREAD

**Issue by lentm88** [inotia00/rvx-builder#111]
**Describe the bug**
I get an java error as below:

`[builder] INFO: Loading patches
[builder] INFO: Setting patch options
[builder] INFO: Decoding app manifest
[builder] INFO: Excluding Custom branding icon MMT
[builder] INFO: Excluding Custom branding icon Revancify blue
[builder] INFO: Excluding Custom branding icon Revancify red
[builder] INFO: Excluding Disable landscape mode
[builder] INFO: Excluding Enable debug logging
[builder] INFO: Excluding Force hide player button background
[builder] INFO: Excluding MaterialYou
[builder] INFO: Excluding Translations
[builder] INFO: Merging integrations
[builder] INFO: Deleting existing resource cache directory
[builder] INFO: Decoding resources
[builder] INFO: Executing patches
[builder] INFO: Add splash animation succeeded
[builder] INFO: Alternative thumbnails succeeded
[builder] INFO: Append time stamps information succeeded
[builder] INFO: Bypass ambient mode restrictions succeeded
[builder] INFO: Change homepage succeeded
[builder] INFO: Custom branding YouTube name succeeded
[builder] INFO: Custom double tap length succeeded
[builder] INFO: Custom package name succeeded
[builder] INFO: Custom playback speed succeeded
[builder] INFO: Custom seekbar color succeeded
[builder] INFO: Default playback speed succeeded
[builder] INFO: Default video quality succeeded
[builder] INFO: Disable QUIC protocol succeeded
[builder] INFO: Disable Shorts on startup succeeded
[builder] INFO: Disable auto captions succeeded
[builder] INFO: Disable haptic feedback succeeded
[builder] INFO: Disable hdr video succeeded
[builder] INFO: Disable pip notification succeeded
[builder] INFO: Enable compact controls overlay succeeded
[builder] INFO: Enable external browser succeeded
[builder] INFO: Enable minimized playback succeeded
[builder] INFO: Enable new comment popup panels succeeded
[builder] INFO: Enable new splash animation succeeded
[builder] INFO: Enable new thumbnail preview succeeded
[builder] INFO: Enable old quality layout succeeded
[builder] INFO: Enable open links directly succeeded
[builder] INFO: Enable seekbar tapping succeeded
[builder] INFO: Enable tablet mini player succeeded
[builder] INFO: Enable tablet navigation bar succeeded
[builder] INFO: Enable wide search bar succeeded
[builder] INFO: Force OPUS codec succeeded
[builder] INFO: Force VP9 codec succeeded
[builder] INFO: Force premium heading succeeded
[builder] INFO: Header switch succeeded
[builder] INFO: Hide account menu succeeded
[builder] INFO: Hide auto player popup panels succeeded
[builder] INFO: Hide autoplay button succeeded
[builder] INFO: Hide autoplay preview succeeded
[builder] INFO: Hide button container succeeded
[builder] INFO: Hide captions button succeeded
[builder] INFO: Hide cast button succeeded
[builder] INFO: Hide category bar succeeded
[builder] INFO: Hide channel avatar section succeeded
[builder] INFO: Hide channel watermark succeeded
[builder] INFO: Hide collapse button succeeded
[builder] INFO: Hide comment component succeeded
[builder] INFO: Hide crowdfunding box succeeded
[builder] INFO: Hide description components succeeded
[builder] INFO: Hide double tap overlay filter succeeded
[builder] INFO: Hide end screen cards succeeded
[builder] INFO: Hide end screen overlay succeeded
[builder] INFO: Hide feed flyout panel succeeded
[builder] INFO: Hide filmstrip overlay succeeded
[builder] INFO: Hide floating microphone succeeded
[builder] INFO: Hide fullscreen panels succeeded
[builder] INFO: Hide general ads succeeded
[builder] INFO: Hide handle succeeded
[builder] INFO: Hide info cards succeeded
[builder] INFO: Hide latest videos button succeeded
[builder] INFO: Hide layout components succeeded
[builder] INFO: Hide load more button succeeded
[builder] INFO: Hide mix playlists succeeded
[builder] INFO: Hide music button succeeded
[builder] INFO: Hide navigation buttons succeeded
[builder] INFO: Hide navigation label succeeded
[builder] INFO: Hide player button background succeeded
[builder] INFO: Hide player flyout panel succeeded
[builder] INFO: Hide player overlay filter succeeded
[builder] INFO: Hide previous next button succeeded
[builder] INFO: Hide quick actions succeeded
[builder] INFO: Hide seek message succeeded
[builder] INFO: Hide seekbar succeeded
[builder] INFO: Hide shorts components succeeded
[builder] INFO: Hide snack bar succeeded
[builder] INFO: Hide speed overlay succeeded
[builder] INFO: Hide suggested actions succeeded
[builder] INFO: Hide suggested video overlay succeeded
[builder] INFO: Hide suggestions shelf succeeded
[builder] INFO: Hide time stamp succeeded
[builder] INFO: Hide tooltip content succeeded
[builder] INFO: Hide trending searches succeeded
[builder] INFO: Hide video ads succeeded
[builder] INFO: Language switch succeeded
[builder] INFO: Layout switch succeeded
[builder] INFO: MicroG support succeeded
[builder] INFO: Overlay buttons succeeded
[builder] INFO: Return YouTube Dislike succeeded
[builder] INFO: Settings succeeded
[builder] INFO: SponsorBlock succeeded
[builder] INFO: Spoof app version succeeded
[builder] INFO: Spoof player parameters succeeded
[builder] INFO: Swipe controls succeeded
[builder] INFO: Theme succeeded
[builder] INFO: Compiling modified dex files
[builder] Exception in thread "main"
[builder] java.lang.OutOfMemoryError: Java heap space
[builder] at java.base/java.util.Arrays.copyOf(Arrays.java:3537) at com.android.tools.smali.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:91)
[builder] at com.android.tools.smali.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:39) at com.android.tools.smali.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:79) at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182) at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:423) at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370) at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:158) at lanchon.multidexlib2.DexIO.access$000(DexIO.java:38) at lanchon.multidexlib2.DexIO$1.call(DexIO.java:99) at lanchon.multidexlib2.DexIO$1.call(DexIO.java:96) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[builder] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:833)`

**To Reproduce**

It looks like the custom package name option makes an issue. No issue without it.

**Screenshots**

**rvx-builder Version:** [e.g. v1.2.10]
v3.9.12 & v3.9.15
**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: Windows 10 Pro

**Additional context**

**Comment by inotia00** [comment]
It's not an issue with rvx-builder

This is an error in revanced-cli, and the content of the error is that the patch cannot be completed because your PC has insufficient RAM

Unfortunately, please use another method to patch
