### ISSUE TITLE
failed mount.sh in termux

### ISSUE THREAD

**Issue by bagus02** [inotia00/rvx-builder#112]
An error occured:Error: Command failed: su -c 'cp "./mount.sh" "/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'cp: bad './mount.sh': No such file or directoryat ChildProcess.exithandler (node:child_process:419:12)at ChildProcess.emit (node:events:513:28)at maybeClose (node:internal/child_process:1091:16)at ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by inotia00** [comment]
fixed in [rvx-builder-v3.10.0](https://github.com/inotia00/rvx-builder/releases/tag/v3.10.0)
