### ISSUE TITLE
Manager, Revancify cannot connect to the GitHub server and cannot be patched

### ISSUE THREAD

**Issue by sssh7710** [inotia00/rvx-builder#113]
**Describe the bug**

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**

![Screenshot_20231003_151956_Termux](https://github.com/inotia00/rvx-builder/assets/98168192/a2a036a3-a47b-4f6f-9fa8-d56b39a428e2)
![Screenshot_20231003_152004_RVX Manager](https://github.com/inotia00/rvx-builder/assets/98168192/621eb234-fcf2-4bf8-9c1d-0bb633e17674)
![Screenshot_20231003_152010_RVX Manager](https://github.com/inotia00/rvx-builder/assets/98168192/d7002980-4b57-4065-b2e2-ce62798ebed4)

**Comment by inotia00** [comment]
It's most likely simply an issue with your internet
The causes may vary, but in my case, the VPN/DNS I was using was blocking the github API
So I solved the issue by turning off VPN/DNS

Anyway, this is not an appropriate issue to write about in the rvx-builder repo
