### ISSUE TITLE
Errors while patching

### ISSUE THREAD

**Issue by Sheldon988** [inotia00/rvx-builder#114]
RVX Builder keeps triggering these errors.
It only happens on this computer, while another one works without problems. The same YT version (18.33.40) has been used, with default patches selected.
Azul JRE 17.44.53 (17.0.8.1) x64 is installed on both machines. I also tried by installing x86 version along with x64.
I tried both using a manually downloaded apk and by choosing the embedded download mode.
Of course I tried several times by completely wiping the RVX folder and %LocalAppData%\Temp.

![2023-10-06_095104](https://github.com/inotia00/rvx-builder/assets/65183470/a83f815c-109b-44ac-b8f2-0954aacb0642)
![2023-10-06_095118](https://github.com/inotia00/rvx-builder/assets/65183470/8522028b-2e60-48df-b472-0f8d7380082f)
![2023-10-06_095136](https://github.com/inotia00/rvx-builder/assets/65183470/30c89b04-486e-45ee-b162-62932de9a13d)

**Comment by inotia00** [comment]
fixed in [rvx-builder-v3.10.0](https://github.com/inotia00/rvx-builder/releases/tag/v3.10.0)
