### ISSUE TITLE
command failed

### ISSUE THREAD

**Issue by ij-israfil** [inotia00/rvx-builder#116]
An error occured:Error: Command failed: su -c pm install -r -d "/data/data/com.termux/files/home/rvx-builder/revanced/com.google.android.youtube.apk"at ChildProcess.exithandler (node:child_process:419:12)at ChildProcess.emit (node:events:513:28)at maybeClose (node:internal/child_process:1091:16)at ChildProcess._handle.onexit (node:internal/child_process:302:5)Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Comment by inotia00** [comment]
fixed in [rvx-builder-v3.10.0](https://github.com/inotia00/rvx-builder/releases/tag/v3.10.0)
