### ISSUE TITLE
Unable to use my existing keystore

### ISSUE THREAD

**Issue by auanasgheps** [inotia00/rvx-builder#117]
**Describe the bug**
Since the latest version, I am unable to use my previous keystore.

If I delete my keystore, I can successfully patch any app by generating a new one.

Do you think this issue is specific to Revanced CLI?

**To Reproduce**

1. Use a previous keystore
2. Patch any app with the latest version
3. An error will appear 

`java.lang.IllegalArgumentException: Keystore does not contain alias ReVanced Key at app.revanced.library.ApkSigner.readKeyCertificatePair(ApkSigner.kt:91) at app.revanced.library.ApkSigner.newApkSignerBuilder(ApkSigner.kt:228) at app.revanced.library.ApkUtils.sign(ApkUtils.kt:79) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:246) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)`

![image](https://github.com/inotia00/rvx-builder/assets/20586878/9c7241ed-d84f-411e-9875-bfa74cf54a1d)

**revanced-builder Version:** 3.10.1
**Desktop (please complete the following information):**

- OS: Windows 
- Version: 10

**Additional context**

**Comment by inotia00** [comment]
bruh this is an issue with the official ReVanced CLI, not with RVX Builder 🙄

You can choose one of the following:

Method 1. Remove the previously used `revanced.keystore`
Method 2. Or simply change the Cli Organization to `inotia00` in the rvx builder settings (my CLI is compatible with the old keystore)

**Comment by auanasgheps** [comment]
Now it is needed to specify the alias for old keystores
https://github.com/ReVanced/revanced-cli/issues/285#issuecomment-1762884953

**Comment by inotia00** [comment]
I emphasize once again that rvx-builder is a fork for compatibility with my source.

In this fork repo, you can only open issues encountered while using my source.

If you want to use the old keystore, use cli, not rvx-builder.
