### ISSUE TITLE
FetchError

### ISSUE THREAD

**Issue by Frank810803** [inotia00/rvx-builder#121]
**Describe the bug**
the bug appears when after upñoading the apk.

**To Reproduce**
Steps to reproduce the behavior: just do the normal steps

**Screenshots**
![image](https://github.com/inotia00/rvx-builder/assets/146159675/8cde6245-86d1-4f18-9701-0cc9f19da3f4)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: RVX.exe v 3.10.1

**Comment by inotia00** [comment]
This error occurs because the Internet you are using cannot connect to APKMirror

Change the DNS or VPN you are using and try again
