### ISSUE TITLE
Kernelsu support?

### ISSUE THREAD

**Issue by ghost** [inotia00/rvx-builder#122]
An error occured:Error: Command failed: su -mm -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'/data/adb/service.d/mount_revanced_com.google.android.youtube.sh[2]: magisk: inaccessible or not foundmount: '/sbin/.magisk/mirror/data/adb/revanced/com.google.android.youtube.apk'->'/data/app/~~4MiQ6knEIME2F1VIxl1-dg==/com.google.android.youtube-a0JOCjBgxVSoyGrEj2sDOA==/base.apk': No such file or directoryat ChildProcess.exithandler (node:child_process:419:12)at ChildProcess.emit (node:events:513:28)at maybeClose (node:internal/child_process:1091:16)at ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by inotia00** [comment]
iirc, ReVanced CLI does not support Kernelsu

Since I'm not a ROOT user, I'm not sure
