### ISSUE TITLE
ERROR WHILE COMPILING MODIFIED RESOURCES FOR YOUTUBE 

### ISSUE THREAD

**Issue by sandirickyroy** [inotia00/rvx-builder#123]
USING:-

RVX BUILDER v3.10.1

OS: WINDOWS 11

ZULU 21.30.15-CA-JDK21.0.1-WIN_X64

FACING THIS ERROR: brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)

SINCE RVX BUILDER v3.10.1 WAS RELEASED, THIS HAS BEEN A SERIOUS PROBLEM.

![Screenshot 2023-10-29 004705](https://github.com/inotia00/rvx-builder/assets/11662005/98556807-946b-4fa7-81ed-5b2f63d3fb0a)

**Comment by inotia00** [comment]
Remove the `options.json` file from the path where rvx-builder.exe exists
And try again and the issue will be resolved

**Comment by sandirickyroy** [comment]
DELETED EVERYTHING, RESTARTED. STILL FACING SAME ERROR.

**Comment by sandirickyroy** [comment]
> Remove the `options.json` file from the path where rvx-builder.exe exists And try again and the issue will be resolved

YOUR SUGGESTION DIDN'T WORK. PLEASE SCRUTINIZE THIS ISSUE.

**Comment by inotia00** [comment]
There will be a folder named `revanced-resource-cache` in the directory where rvx-builder exists.
Please compress the `res` directory under `revanced-resource-cache` and then upload it

※ And don't write your content in capital letters

**Comment by thisissinior** [comment]
hi there mate! thanks for the builder, I used it once before and have a working app on my phone right now, but not all premium features are working, no premium logo and I see ads again, I wanted to do a fresh apk but I confronted errors, I tried to delete all the files for a fresh start but the error remains the same, I'll attach screenshots, it would be a great help if you find out what I'm doing wrong
![Screenshot 2023-10-30 231143](https://github.com/inotia00/rvx-builder/assets/67796095/5d6f4c00-a0ce-4bca-a477-3737c62df990)
![Screenshot 2023-10-30 23091822](https://github.com/inotia00/rvx-builder/assets/67796095/241294fe-9112-4b16-80f5-d885b7557c79)

**Comment by sandirickyroy** [comment]
There you go...
[res.zip](https://github.com/inotia00/rvx-builder/files/13220968/res.zip)

**Comment by inotia00** [comment]
> hi there mate! thanks for the builder, I used it once before and have a working app on my phone right now, but not all premium features are working, no premium logo and I see ads again, I wanted to do a fresh apk but I confronted errors, I tried to delete all the files for a fresh start but the error remains the same, I'll attach screenshots, it would be a great help if you find out what I'm doing wrong

This is another issue unrelated to this issue
Please open a new issue

**Comment by inotia00** [comment]
> There you go... [res.zip](https://github.com/inotia00/rvx-builder/files/13220968/res.zip)

I checked the file you attached

It is assumed to be an error in Apktool, but it does not reproduce on my PC

Since it was presumed to be an error in Apktool, I downgraded the Apktool version of ReVanced CLI for testing purposes

revanced-cli-v4.0.4 (test build)
https://we.tl/t-6uIBmf8FJU

There will be a folder named `revanced` in the directory where rvx-builder exists.

Overwrite `revanced-cli-v4.0.4.jar` there

Then run rvx-builder again and test whether the issue is resolved

**Comment by sandirickyroy** [comment]
It stopped after decoding resources for almost 12 minutes and then took another 6 minutes at "Compiling modified resources" stage and in the end It failed to compile and shows the same error message.

[res.zip](https://github.com/inotia00/rvx-builder/files/13224377/res.zip)

![image](https://github.com/inotia00/rvx-builder/assets/11662005/25a088dc-9ad9-4c60-b45c-b4da08a943c6)

**Comment by inotia00** [comment]
If so I have no idea

I'm leaving the issue open because people who visit this page with the same issue may provide useful information.

**Comment by sandirickyroy** [comment]
You may now close it.
After erasing every folder and downloading RVX-Builder again, I had to start over in order to address the issue and eventually it functioned.
![Screenshot 2023-11-02 125356](https://github.com/inotia00/rvx-builder/assets/11662005/dfd74943-03b4-4bec-b4da-d360015e5f39)

**Comment by inotia00** [comment]
It's weird, but I'm glad your issue is resolved
