### ISSUE TITLE
downgrading revanced patches.

### ISSUE THREAD

**Issue by bobrobigi** [inotia00/rvx-builder#126]
Is there anyway to downgrade the version of the patches for an older one? it doesnt matter if its on the builder or the manager, i just really need a patch that was removed in an older version.
if not, would you mind adding an option to upload the patches.jar you want on the manager or is that a problem of revanced and not revanced extanded?
thanks anyway

**Comment by inotia00** [comment]
For some reason, Github notifications for issues opened in the rvx-builder repo were not received, so I only checked this issue today.

this is not that difficult

First, download the `revanced-patches` and `revanced-integrations` you want to downgrade to
`revanced-patches` and `revanced-integrations` must match, downloading builds with the same release date

If you are not sure exactly when `revanced-patches` and `revanced-integrations` were released, you can check them in the [Github notification Telegram channel](https://t.me/revanced_extended_repo)

For example, [revanced-patches-2.195.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.12) and [revanced-integrations-0.120.12](https://github.com/inotia00/revanced-integrations/releases/tag/v0.120.12) were released on the same day
Let's take this as an example

Download the following three files:
```
- revanced-patches-2.195.12.jar
- patches.json
- revanced-integrations-0.120.12.apk
```

Then, change the name of the downloaded file to match the format of the latest version.

The latest builds as of now are `revanced-patches-2.196.7` and `revanced-integrations-0.121.7`
```
- revanced-patches-2.195.12.jar
- patches.json
- revanced-integrations-0.120.12.apk
```

Change the names of these files as follows:
```
- revanced-patches-v2.196.7.jar
- revanced-patches-v2.196.7.json
- revanced-integrations-v0.121.7.apk
```

**Case 1. If you are using rvx-builder (Windows, Linux, MacOS)**

There will be a `revanced` folder in the directory where rvx-builder exists.

Overwrite the following files in the `revanced` folder.
```
- revanced-patches-v2.196.7.jar
- revanced-patches-v2.196.7.json
- revanced-integrations-v0.121.7.apk
```

Now launch rvx-builder and proceed with the patch.

**Case 2. If you are using rvx-builder (Android/Termux)**

The overall method is similar, but you will need the following app to access the directory where rvx-builder resides:

[Files by Marc](https://play.google.com/store/apps/details?id=com.marc.files)

First, open Files by Marc and click the menu button (☰) in the upper left corner.

There will be `Termux` at the bottom. Click on this

Go to home/rvx-builder/revanced

Please remove all files except `revanced.keystore`

Copy the following files to (Termux)/home/rvx-builder/revanced
```
- revanced-patches-v2.196.7.jar
- revanced-patches-v2.196.7.json
- revanced-integrations-v0.121.7.apk
```

Now launch rvx-builder and proceed with the patch.

**Comment by bobrobigi** [comment]
You sure i dont need to downgrade the cli and builder?

**Comment by inotia00** [comment]
which patch versions did you tried?

**Comment by bobrobigi** [comment]
> which patch versions did you tried?

Really sorry for not responding, I used the one you released on July 24. And I'm talking about the one with microg patches.

**Comment by inotia00** [comment]
In this case, the cli and rvx-builder must also be downgraded

I will explain based on the build released on July 24

Download files from the following link:

[rvx-builder](https://github.com/inotia00/rvx-builder/releases/tag/v3.9.5)
[revanced-cli.jar](https://github.com/inotia00/revanced-cli/releases/tag/v2.22.2)
[revanced-patches.jar, patches.json](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
[revanced-integrations.apk](https://github.com/inotia00/revanced-integrations/releases/tag/v0.114.1)

```
revanced-cli-2.22.2-all.jar
revanced-patches-2.186.1.jar
patches.json
revanced-integrations-0.114.1.apk
```
Change the names of these files as follows:
```
revanced-cli-v4.3.1.jar
revanced-patches-v2.202.1.jar
revanced-patches-v2.202.1.json
revanced-integrations-v0.125.1.apk
```

**Case 1. If you are using rvx-builder (Windows, Linux, MacOS)**

There will be a `revanced` folder in the directory where rvx-builder exists.

Overwrite the following files in the `revanced` folder.
```
revanced-cli-v4.3.1.jar
revanced-patches-v2.202.1.jar
revanced-patches-v2.202.1.json
revanced-integrations-v0.125.1.apk
```

Now launch [rvx-builder](https://github.com/inotia00/rvx-builder/releases/tag/v3.9.5) and proceed with the patch.

The supported YouTube version is probably `v18.27.36`

**Case 2. If you are using rvx-builder (Android/Termux)**

Unfortunately, the rvx-builder (Android/Termux) method is very complicated and difficult to explain

If you have a PC, be sure to follow the PC method
