### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by Tronak007** [inotia00/rvx-builder#128]
I Don't Know What This Error Is About But I'm Having This Issue While Installing ReVanced Manager On Termux, Attaching The Screenshot Of The Error,

Please Help And If It's A Old Problem Then When You Close This Issue Please Put A Comment In Which Number I Can Solve It

Thanks In Advance
![Screenshot_20231116-002252.png](https://github.com/inotia00/rvx-builder/assets/106589892/9dfab2c0-460a-40fe-942b-cfc835726675)

**Comment by inotia00** [comment]
I also had a similar issue, and I think the issue was caused by one of termux's dependency modules failing to update.

I solved the issue by reinstalling termux.
