### ISSUE TITLE
temp.apk rename error if file exists 

### ISSUE THREAD

**Issue by tooruu** [inotia00/rvx-builder#133]
```
[builder] An error occured:Error: EPERM: operation not permitted, rename './revanced/temp.apk' -> './revanced/com.google.android.youtube.apk'
at renameSync (node:fs:1038:3)
at C:\snapshot\rvx-builder\utils\uploadAPKFile.js:23:11
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
**To reproduce:**
1. Have file named `com.google.android.youtube.apk` in the folder
2. Upload YouTube APK

**rvx-builder Version:** v3.11.1

**Desktop OS:** Windows 11 (22621.1555)

**Possible solution:**
Delete existing apk on startup.

**Comment by inotia00** [comment]
You uploaded the apk in `revanced` directory

This is not the intended behavior, as it uploads the apk being used in rvx-builder's working directory

> 1. Have file named `com.google.android.youtube.apk` in the folder
> 2. Upload YouTube APK

If filename `com.google.android.youtube.apk` exists in `revanced` directory, just don't upload APK

There is already an option to use the previously downloaded APK as is
