### ISSUE TITLE
ERROR START PATCHING

### ISSUE THREAD

**Issue by SYS6-LorenzoC** [inotia00/rvx-builder#135]
THE ERROR COMES UP AS SOON AS I START THE PROGRAM.
TRIED ON 2 PCS SAME ERROR

![Screenshot 2023-12-27 141554](https://github.com/inotia00/rvx-builder/assets/79712791/852d4c59-99a5-4ae3-b184-e1ee4abbc2cd)

**Comment by inotia00** [comment]
Github API cannot be fetched on the device you are using

Change your Internet environment
