### ISSUE TITLE
Slide control is too close to the other controls : maximize, speed controller, copy url control...

### ISSUE THREAD

**Issue by PerfKeeper** [inotia00/rvx-builder#137]
Hi 
Thanks you for your well done job around YouTube ReVanced extended.

Here I share with you an inconvenience related to the position of the controls.

Because slide control is too close to the other controls : the maximizer, speed controller, copy url control...etc, when I try to click on of thoses controls, I change by mistake the position of reading of my video.

Example 

> I am on the beginning of a given video, 
> I want to maximaize the video to the screen size, 
> The video reading cursor is now at the end because my finger is too big 😄 or the maximize button is just to close to the sliding control.

I suggest to move other controls like the maximazer, upper a little bit, and position them on the right or left side.

I suggest also, to reduce the size of the slider by giving it some margins at the left and the right sides, to have better control when moving the reading cursor. Its somehow difficult to move the cursor at the left or right parts of the slider when the video is in normal size, even on a phone of 7 or 8 cm of screen width.

Thanks in advance

Regards

**Comment by inotia00** [comment]
This repository is for Builders, not Patches.
