### ISSUE TITLE
VancedMicroG is no longer needed. Download the GmsCore instead?

### ISSUE THREAD

**Issue by yuukiAme** [inotia00/rvx-builder#138]
Since Revanced-patch v 4.7.0, VancedMicroG is no longer needed. 

The auto download dependency is still checking and downloading `VancedMicroG-v0.3.0.234914.apk` 

Why isn't the RVX-builder auto download GmsCore instead?

`VancedMicroG-v0.3.0.234914.apk` is still being download when installing with RVX-builder.

**Comment by inotia00** [comment]
It follows the values specified in `Settings` - `Sources` - `MicroG Source`

If you change this value, ReVanced MicroG will be downloaded

The default value for MicroG Source will probably change in the next rvx-builder release

**Comment by yuukiAme** [comment]
Okay. Thank you.

I will change the value in rvx-builder to Revanced GmsCore for now.

![2024_05_27_15_22_32_firefox](https://github.com/inotia00/rvx-builder/assets/45681604/6deb9304-0565-44ea-aa75-3d5b2341b31c)
