### ISSUE TITLE
[Bug] Error fetching APKs

### ISSUE THREAD

**Issue by ItsMe-Haris** [inotia00/rvx-builder#142]
**Describe the bug**
Error occurs after selecting an app and clicking continue. Maybe the apk scrapper is broken.

**To Reproduce**

1. Click 'Start Patching'
2. Let it download dependencies & click "Continue"
3. Select any app & click "Continue"

**Screenshots**
<img src="https://github.com/user-attachments/assets/ad32b0c8-101f-446f-907f-d5e88eeab64a" alt="app-selection" width="768px" >

<img src="https://github.com/user-attachments/assets/c921676c-732e-495c-9304-6b7e0a2b260f" alt="error-screen" width="768px" >

**rvx-builder Version:** v3.15.1

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 Pro x64

**Comment by inotia00** [comment]
Might fixed in latest release
