### ISSUE TITLE
Custom Package Name

### ISSUE THREAD

**Issue by AlexanderQueen** [inotia00/rvx-builder#149]
![image](https://github.com/user-attachments/assets/c350a646-380d-4b57-a03f-ca0dd22a62f4)|

I want to use custom package name (original), but the builder gives me that error. Is this possible to use original package name or not?

**Comment by KobeW50** [comment]
It is impossible to install patched YT with the regular package name (`com.google.android.youtube`) unless u do a root (mount) installation, for which you must exclude the `GmsCore support` patch
