### ISSUE TITLE
Error: EBUSY: resource busy or locked, unlink ?

### ISSUE THREAD

**Issue by Skrell** [inotia00/rvx-builder#15]
**Describe the bug**
I've tried the latest version of you builder on 2 Window's machines now and both give me the same error during the compilation process.  I get : 
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\vmb11\Desktop\Revanced\revanced-cache\1.apk'

**To Reproduce**

Just run it on Windows 10 or 11

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]
3.4.16

**Desktop (please complete the following information):**

- OS: Windows 11 or 10
- Version: home x64

**Additional context**
Node.js v19.0.1
Zulu JDK v17.38.21

**Comment by Spacellary** [comment]
You can try the steps at https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651 and see if that works, if it does or doesn't even after reboot, check your Windows Environment PATHS and make sure the new JDK is set to the right Path in there. Hopefully this helps.

**Comment by inotia00** [comment]
duplicate https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
