### ISSUE TITLE
Patching successful but app not saved and installation failed

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/rvx-builder#150]
After every release of new patches, patching YouTube for the first time with that new patch shows this issue. YouTube patched successfully but cannot install it or save the patched app. Then you have to again patch YouTube app for installation and for saving the patched app. This issue only arise one time with every release of new patch.

RVX Manager Version: v1.22.1

**Comment by inotia00** [comment]
This repository is for Builders, not Manager.
