### ISSUE TITLE
Feature Request: Removal of Some Elements

### ISSUE THREAD

**Issue by sam619007** [inotia00/rvx-builder#154]
Kindly provide a feature to hide the elements encircled in red in the attached images.
![IMG_20241025_190617](https://github.com/user-attachments/assets/7179461e-bafb-4b83-ba07-82cc200d3535)
![IMG_20241025_190537](https://github.com/user-attachments/assets/57457572-b8bb-413f-ada0-83a91dfe6f27)
![IMG_20241025_184819_057](https://github.com/user-attachments/assets/f56740b7-04b4-43f0-b2cb-9395b4133849)

**Comment by inotia00** [comment]
This repository is for Builders, not Patches.
