### ISSUE TITLE
Bug: Anti-Split fails if file path contains spaces

### ISSUE THREAD

**Issue by Charu-Mahbub** [inotia00/rvx-builder#158]
![ScreenShot_2024-11-21_010455](https://github.com/user-attachments/assets/e2cb1800-8e31-4fb9-918c-68f84fafaf41)

**rvx-builder Version:** [e.g. v3.11.1]

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10 x64

**Additional context**

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/rvx-builder/issues/147
