### ISSUE TITLE
EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by jay5656** [inotia00/rvx-builder#159]
**Describe the bug**
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:747:3)
    at Object.readSync (pkg/prelude/bootstrap.js:944:32)
    at tryReadSync (node:fs:447:20)
    at Object.readFileSync (node:fs:493:19)
    at readFileSync (pkg/prelude/bootstrap.js:1079:36)
    at getPatches (C:\snapshot\rvx-builder\wsEvents\getApp.js:33:5)
    at WebSocket.<anonymous> (C:\snapshot\rvx-builder\index.js:183:15)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (C:\snapshot\rvx-builder\node_modules\ws\lib\websocket.js:1211:20)
    at Receiver.emit (node:events:537:28)

**To Reproduce**

1. run rvx builder
2. set sources as revanced 
3. click continue 

**Screenshots**

**rvx-builder Version:** 
3.16.1

**Desktop (please complete the following information):**

- OS: Windows 
- Version: 11

**Additional context**
i only have 3 patch options (reddit, youtube/music) when last month i had options for many more cause i had the ability to patch tiktok and duolingo

**Comment by aleislost** [comment]
it's happening to me as well, Windows 10

**Comment by SalmeBale** [comment]
same issue

**Comment by Diyagi** [comment]
Thats because revanced patches are shipped not as an `.jar` but as `.rvp`.
This causes this condition https://github.com/inotia00/rvx-builder/blob/170972367946808c84a8fcfbcd4aff486886e8ea/utils/FileDownloader.js#L28 to fail as it expects an `.jar` file.

**Comment by jay5656** [comment]
> Thats because revanced patches are shipped not as an `.jar` but as `.rvp`. This causes this condition
> 
> https://github.com/inotia00/rvx-builder/blob/170972367946808c84a8fcfbcd4aff486886e8ea/utils/FileDownloader.js#L28
> 
> to fail as it expects an `.jar` file.

how can i fix this?

**Comment by Diyagi** [comment]
> Thats because revanced patches are shipped not as an `.jar` but as `.rvp`. This causes this condition
> 
> https://github.com/inotia00/rvx-builder/blob/170972367946808c84a8fcfbcd4aff486886e8ea/utils/FileDownloader.js#L28
> to fail as it expects an `.jar` file.


Actually theres more than that, with the v5 they are not shipping the `patches.json` in the repo anymore, this is now fetched from their [API](https://api.revanced.app/v4/patches/list), the structure of the json itself also changed a bit.

**Comment by inotia00** [comment]
Might fixed in latest release
