### ISSUE TITLE
ARSClib toggle seems to be missing in latest rvx-builder 3.18.2 (PC)

### ISSUE THREAD

**Issue by uvmhbn** [inotia00/rvx-builder#171]
The ARSClib toggle does not appear in the settings in the latest rvx-builder 3.18.2 (PC version).

Open the settings page.

**Comment by ghost** [comment]
It's intended, read [release notes](https://github.com/inotia00/rvx-builder/releases/tag/v3.18.1)

**Comment by uvmhbn** [comment]
apologies for not RTFM.
