### ISSUE TITLE
Error just before patching app

### ISSUE THREAD

**Issue by nick-77** [inotia00/rvx-builder#172]
**Describe the bug**
error popping up at "selecting app version" step

**To Reproduce**

1. Start rvx builder 
2. Select reddit app 
3. Select patches
4. Error pops up at selecting app version step

**Screenshots**
![IMG_20241223_015559.jpg](https://github.com/user-attachments/assets/d23ca39c-e2d3-4515-b764-6419050e9719)

**rvx-builder Version:** [3.18.2] (android)

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**
Tried reinstalling rvx builder as well using "rvxre", still facing error

**Comment by nick-77** [comment]
Update: it's working fine now, not sure what happened, I haven't done anything. Anyways sorry for the trouble. Kindly close the issue

**Comment by inotia00** [comment]
It looks like an issue that was on APKMirror last week
