### ISSUE TITLE
EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by Totozao** [inotia00/rvx-builder#18]
**Describe the bug**
Final compilation of Youtube app getting error

**To Reproduce**

1. Try to compile YouTube App
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45948675/200877947-6ac86fd9-d063-4e26-9dbd-725da35ebef7.png)

Revanced builder 3.4.16, with 3.4.15 everything works fine with the same patches

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: Build 25321

**Additional context**
Here is my patch list:
        "overlay-buttons",
        "hide-cast-button",
        "return-youtube-dislike",
        "custom-branding-icon-revancify",
        "materialyou",
        "hide-pip-notification",
        "extended",
        "sponsorblock",
        "minimized-playback",
        "translations",
        "microg-support",
        "optimize-resource",
        "video-ads",
        "general-ads"

**Comment by inotia00** [comment]
duplicate https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
