### ISSUE TITLE
Mount Error

### ISSUE THREAD

**Issue by some1onLSD** [inotia00/rvx-builder#2]
[Builder] An error occured:Error: Command failed: su -c 'cp "./mount.sh" "/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'cp: /data/adb/service.d/mount_revanced_com.google.android.youtube.sh: No such file or directoryat ChildProcess.exithandler (node:child_process:400:12)at ChildProcess.emit (node:events:513:28)at maybeClose (node:internal/child_process:1093:16)at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by some1onLSD** [comment]
rvx-builder v3.4.15
revanced cli v2.14.1
revanced integrations v0.51.0
revanced patches v2.81.2

**Comment by inotia00** [comment]
> 
sorry for the late reply

Please check the checklist below

- Remove the previously installed ReVanced module
- Remove `/data/adb/service.d`
- `/data/dab/revanced`
- Install YouTube on your device before starting the patch (e.g. if you want to patch YouTube v17.40.41, first install YouTube v17.40.41 on your device and proceed with the patch)

**Comment by some1onLSD** [comment]
Hu, thanks for replying..
I tried all that before with the version at that time being v17.39.35 but I got no luck with it, I even reinstalled termux deleted all magisk modules and reinstalled magisk. but still the same issue...can't mount revanced. Also youtube app was installed with the same version as in the installer..
