### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mountaincastle47** [inotia00/rvx-builder#20]
You have an outdated version of JDK.Please get it from here: https://www.azul.com/downloads/?version=java-17-lts

I already installed the latest jdk 17 and rebooted my pc.

**Comment by Spacellary** [comment]
Try installing latest Zulu Open JDK 19 instead.

**Comment by Spacellary** [comment]
My friend, any luck so far? 🙏

**Comment by mountaincastle47** [comment]
Shet man I'm so sorry but my pc is uhh well destroyed due to some unfortunate circumstances and is in repair so I'll let you know in a few days. Once again I'm sorry

**Comment by Spacellary** [comment]
No problem man! Rough situation, hope everything is fixed soon!

**Comment by mountaincastle47** [comment]
Idk if it was because of the java 17 as i had to change my c drive but it works now on java 19. Thanks!

**Comment by mountaincastle47** [comment]
Error: EBUSY: resource busy or locked, unlink '\\?\E:\program\Revanced Extended\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:186:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Comment by mountaincastle47** [comment]
i rebooted the pc multiple times in case of some rogue program fucking up the process but nothing :(

**Comment by Spacellary** [comment]
Maybe the steps and options in this thread do something for you.
https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651

<hr>
Or you could use the `docker-compose` building method for a guaranteed clean environment for building:

1. Install `Git` if you don't have it already.
2. Install and make sure `Docker Desktop` is running.
3. I recommend making a new empty folder.
4. Right click inside it and "Open a Terminal" here.
5. Run `git clone` **this repository**.
6. `cd` into the newly created revanced repository folder.
7. Run `git checkout revanced-extend`
8. Follow the rest of the instructions to Build in the main page here.

**Comment by mountaincastle47** [comment]
i am officially giving up :( i am just gonna try with another computer

**Comment by Spacellary** [comment]
It should work then. It goes away in a clean environment like Windows Sandbox or a VM, or even just another PC.

Good luck! 🤞

**Comment by mountaincastle47** [comment]
it works lol fml
