### ISSUE TITLE
Process Failed 

### ISSUE THREAD

**Issue by NeeRaj-2401** [inotia00/rvx-builder#21]
**Screenshots**
![image](https://user-images.githubusercontent.com/88180887/202731641-c6d71a9d-cdeb-4b54-b4ed-49939929c176.png)

**revanced-builder Version:** v3.5.0

**Desktop (please complete the following information):**

- OS:  Windows
- Version: 10

**Comment by inotia00** [comment]
duplicate https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
