### ISSUE TITLE
Revanced Icons Error

### ISSUE THREAD

**Issue by thiaguinho4** [inotia00/rvx-builder#22]
I built revanced normally with no errors, but the revancify icon doesn't work, and it only appears on the splash screen when you open the app, on the home screen you get the normal youtube icon.

**Comment by thiaguinho4** [comment]
![Screenshot_20221127-222408_One UI Home](https://user-images.githubusercontent.com/101910294/204172525-5bc18c1e-1b17-42eb-a701-f22458bf607b.png)

**Comment by inotia00** [comment]
In the root environment, you must reboot after installation to change the icon.
