### ISSUE TITLE
[revanced-cli] output signed apk filesize vary difference up to 700kb 

### ISSUE THREAD

**Issue by Sappurit** [inotia00/rvx-builder#26]
**Describe the bug**
[revanced-cli] output signed apk filesize vary difference up to 700kb

**To Reproduce**
`java.exe -jar revanced-cli-2.15.2-all.jar -b revanced-patches-2.111.4.jar -m app-release-unsigned-0.71.1.apk --keystore=revanced.keystore -c -t %temp%/ReVanced-Cache -a com.google.android.youtube_17.34.36.apk -o app.revanced.android.youtube_17.34.36_arm64-v8a.apk --rip-lib=armeabi-v7a --rip-lib=x86 --rip-lib=x86_64`

**Desktop (please complete the following information):**
- OS: Windows 7 X64 Enterprise

**Additional context**
```
89,993,575    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.1
89,887,079    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.2
89,985,383    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.3
90,055,015    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.4
89,538,919    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.5
89,649,511    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.6
90,087,783    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.7
90,280,295    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.8
89,960,807    app.revanced.android.youtube_17.34.36_arm64-v8a.apk.9
```
The output filesize varies too much ~700kb. 
I used revanced.keystore from the first run. Then I can update the app in the future.
I generated 9 times and keep the lowest one for my friends.

**Comment by inotia00** [comment]
Current CLI contains align in the compilation process.

In addition, some file size fluctuations also occur in the process of reorganizing the DEX file.
(Because of apktool's bugs, this process is essential)

Therefore, a slight error occurs every time you try to compile, which is normal.
