### ISSUE TITLE
cast button is not showing

### ISSUE THREAD

**Issue by tole2k** [inotia00/rvx-builder#30]
**Describe the bug**

Although unselect hide cast button, cast button is not showing in revanced Youtube
"Hide cast button option" is ON in the setting menu of revanced setting.
if i off the option, i can see cast button. but can't connect TV

**revanced-builder Version:** 
v3.7.0

**Desktop (please complete the following information):**

- OS: Windows
- Version:  10

**Comment by inotia00** [comment]
you have to turn OFF it
