### ISSUE TITLE
Cannot find Download patches

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/rvx-builder#34]
Dear sir, today I built an apk with your rvx-builder but I can't find Download patches. Can you help me, thanks!
![image](https://user-images.githubusercontent.com/70064328/209653414-f167fb25-6b5d-4163-8714-5c2fb2847bc1.png)

**Comment by Spacellary** [comment]
There's isn't a separate "downloads" in Revanced Extended.
If I had to guess it's already included in the `overlay-buttons` or another related one.

**Comment by inotia00** [comment]
Someone who had already replied on behalf of me explained well
