### ISSUE TITLE
error message after patching is finished?

### ISSUE THREAD

**Issue by eepy-creepy** [inotia00/rvx-builder#35]
got this error message right at the end of patching normal youtube. the program generates the revanced apk, and even said "Finished" for a moment before i got the error. however, trying to open the apks gives me a "There was a problem parsing the package" error.
![error-report](https://user-images.githubusercontent.com/121517818/209715339-5195e024-e4fd-4819-9a03-e6b938cfbb4d.png)

patches applied are as follows:
Client Spoof
Custom Branding Icon Revancify
Custom Branding Name
Enable Old Layout
Enable Old Seekbar Color
Enable Seekbar Tapping
Hide Create Button
Hide General Ads
Hide Shorts Button
Hide Shorts Component
Hide Startup Shorts Player
Hide Stories
Hide Video Ads
Microg Support
Optimize Resource
Patch Options
Return Youtube Dislike
Settings
Sponsorblock
Theme

program version 3.7.0

os: windows 10

**Comment by ald53** [comment]
https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1345673718

Happened to me earlier today, doing a clean reinstall of Zulu 32bit works.

**Comment by Spacellary** [comment]
Aye, what ald53 said.
I was also victim of this issue a while back.
Here you go: https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
It was also recommended to install the 32 bit version of JDK, and make sure you check the "Set JAVA_HOME" during the new installation~

**Comment by inotia00** [comment]
This is a duplicate issue
