### ISSUE TITLE
Error: resource busy or locked, error for 3.7.0

### ISSUE THREAD

**Issue by Noir16** [inotia00/rvx-builder#36]
**Describe the bug**
Error: EBUSY: resource busy or locked

**To Reproduce**
When patching `YouTube music`, the YouTube app patched normally.

**revanced-builder Version:**
`3.7.0`

**Desktop (please complete the following information):**

- OS: `Microsoft Windows`
- Version: `10 Build:19045.2364`

**Additional context**
[builder] An error occured:
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\​[Username]\Desktop\revanced-cache\1.apk'
at unlinkSync (node:fs:1780:3)
at _unlinkSync (node:internal/fs/rimraf:214:14)
at rimrafSync (node:internal/fs/rimraf:195:7)
at node:internal/fs/rimraf:253:9
at Array.forEach ()
at _rmdirSync (node:internal/fs/rimraf:250:7)
at rimrafSync (node:internal/fs/rimraf:193:7)
at rmSync (node:fs:1274:10)
at afterBuild (C:\snapshot\revanced-builder-test\wsEvents\patchApp.js:28:3)
at Socket. (C:\snapshot\revanced-builder-test\wsEvents\patchApp.js:185:53)

**Comment by Noir16** [comment]
Duplicate checked: https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
In a previous question https://github.com/inotia00/rvx-builder/issues/24#issuecomment-1358718810 I was advised to use Zulu JDK 32Bit to minimize build issues, but for some reason `3.7.0` uses the built-in Zulu JDK 64Bit.

For music, patching was successful using `3.5.0` and Zulu JDK 32Bit.

**Comment by Spacellary** [comment]
###### This never stops haunting us.
Let's see what's going on this time...
### Can you provide the following information:
1. Does it reproduce in the upstream [Revanced Builder](https://github.com/reisxd/revanced-builder)?
2. What does the `java --version` command return in your Terminal?

Here's mine for comparison, and for later context:
``` pwsh
openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Zulu17.38+21-CA (build 17.0.5+8-LTS)
OpenJDK Client VM Zulu17.38+21-CA (build 17.0.5+8-LTS, mixed mode, emulated-client)
```
<hr>

So I did try running `rvx-builder-win` version `3.7.0` and with the above java versions installed it actually did not download anything else related to that, it just used the version I have installed. I built both YouTube and YouTube Music **Extended** without issues.

I have the Zulu JDK 17 17.0.5 (64-bit) installed. 

_Luckly no issues so far._

**Comment by Noir16** [comment]
1. Revanced Builder always maintains the latest version.
2. I have already installed Zulu version, and I mentioned that I am using the 64Bit Zulu JDK on 3.7.0.

**Comment by Noir16** [comment]
Closed issue as per version update.
