### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tranngoc7782** [inotia00/rvx-builder#43]
{can't build youtube revanced extended v18.04.35...the patching process is stuck at the end of the process. i used the latest rvx-builder-win v3.8.0}

**Comment by tranngoc7782** [comment]
[builder] WARNING: C:\Users\trann\Downloads\.\revanced-cache\res\values\public.xml:13191: error: no definition for declared symbol 'app.rvx.android.youtube:drawable/generic_dark_x1'.
[builder] WARNING: C:\Users\trann\Downloads\.\revanced-cache\res\values\public.xml:13192: error: no definition for declared symbol 'app.rvx.android.youtube:drawable/generic_light_x1'.
[builder] WARNING: error: failed linking references.

**Comment by Zahied917** [comment]
Sir app is not opened .

**Comment by inotia00** [comment]
not rvx builder issue
