### ISSUE TITLE
Please report this bug

### ISSUE THREAD

**Issue by ANGry098** [inotia00/rvx-builder#44]
**Describe the bug**

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**
![vanced](https://user-images.githubusercontent.com/84491262/215557648-ece332cc-e336-4b32-a5b3-fef71ae85b14.png)

**Comment by thiensniper** [comment]
I have the same issue :((

**Comment by Spacellary** [comment]
You probably have already, but it of you didn't, try a few solutions proposed here in https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651.

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651

**Comment by thiensniper** [comment]
@ANGry098 Try clone source and using docker-compose to build and deploy will work for any desktop (Only need docker desktop).

**Comment by Spacellary** [comment]
@thiensniper This really. The Docker Compose has been the **only**completely reliable method I've used.
I can't recommend it enough for people with complex or historied environments.
