### ISSUE TITLE
fail after reaching choosing patches section

### ISSUE THREAD

**Issue by OkYouReallyGood** [inotia00/rvx-builder#45]
**Describe the bug**
After downloading everything when it reaches the point of choosing patches, this error happens:
 An error occured:FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0 at /data/data/com.termux/files/home/rvx-builder/node_modules/node-fetch/lib/index.js:273:32 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async fetchPackages (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:19:20) at async getPatches (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:40:16) at async WebSocket.

**To Reproduce**

1. Run rvx builder in termux
2. Go to localhost
3. Download everything in local host
4. See error, when you reach "choose your patches 

**Screenshots**
![InShot_20230131_010814127](https://user-images.githubusercontent.com/117198136/215595519-9fcdfe9d-c089-457d-80b8-87d2dfe29c56.jpg)

**revanced-builder Version:** 
3.8.0
**Desktop (please complete the following information):**

- OS: Android 
- Version: 11

**Additional context**
Thise problem didn't happen before

**Comment by inotia00** [comment]
In certain countries, it is not possible to access the apkmirror domain.
(e.g. Some China ISP)

Among the issues reported in the past, there were similar issues.

Perhaps this is the cause
Use VPN
