### ISSUE TITLE
App crash on first launch

### ISSUE THREAD

**Issue by Thai2706** [inotia00/rvx-builder#47]
**Describe the bug**
[Bug description](https://paste.crdroid.net/dXKqqO)

**To Reproduce**

1. Install microG via adb
2. Install rvx via adb
3. Open app
4. App crash

ReVanced-Extended-18.04.35

- OS: crDroid 9 (Android 13) POCO X3 NFC

**Comment by inotia00** [comment]
The place to report the issue is wrong
