### ISSUE TITLE
can you add newpipe download integrations back

### ISSUE THREAD

**Issue by mountaincastle47** [inotia00/rvx-builder#48]
please

**Comment by mountaincastle47** [comment]
![Uploading Screenshots_2023-02-03-22-30-50.png…]()

**Comment by Spacellary** [comment]
Settings > ReVanced > Overlay Button Settings > Downloader

You can pick New Pipe and New Pipe + Sponsorblock.

**Comment by mountaincastle47** [comment]
No downloader options is found in the building options

**Comment by Spacellary** [comment]
There is no specific downloader patch to add during building here in Extended. It is likely built into other patches, such as `overlay-buttons` or something else. Just select all patches when building, maybe remove the `hide-overlay-filter` and of course pick the theme you want. The "select all" button at the top works well enough for most people.

**Comment by mountaincastle47** [comment]
> There is no specific downloader patch to add during building here in Extended. It is likely built into other patches, such as `overlay-buttons` or something else. Just select all patches when building, maybe remove the `hide-overlay-filter` and of course pick the theme you want. The "select all" button at the top works well enough for most people.

thanks that option worked :D
