### ISSUE TITLE
Module not found error when trying to run rvx-builder

### ISSUE THREAD

**Issue by enusri** [inotia00/rvx-builder#55]
Node.js v18.14.1
~ $ ./rvx-builder.sh                                    
[rvx-builder] Already gotten storage access.            
[rvx-builder] Node.js and JDK already installed.
[rvx-builder] rvx-builder found.
[rvx-builder] All checks done.

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/data/data/com.termux/files/home/rvx-builder'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.14.1

That is what i am getting when trying to run the builder, i tried the options in documentation but it doesn't help. Please anyone tell me a solution for this.

Thank you.

**Comment by inotia00** [comment]
Sometimes packages are not installed properly if the connection to the termux repository in your region is unstable.

then this error occurs

just reinstall rvx-builder

`./rvx-builder.sh reinstall && ./rvx-builder.sh run`
