### ISSUE TITLE
error when trying to compile youtube

### ISSUE THREAD

**Issue by koullis22** [inotia00/rvx-builder#58]
got this error 

![Screenshot_20230221_103817_com duckduckgo mobile android](https://user-images.githubusercontent.com/31069905/220613497-e45c0008-c92c-48f9-a97c-0d990bb83a9a.jpg)

**Comment by inotia00** [comment]
turn off your VPN

**Comment by koullis22** [comment]
firstly it wasnt vpn..its tracking option from duckduckgo and secondly i tried again without it. same error!

**Comment by inotia00** [comment]
This error occurs when APKMirror cannot be parsed.

do the following
==
Method 1. Change VPN to OFF
Method 2. Reinstall rvx-builder
Method 3. Upload the APK to rvx-builder

**Comment by koullis22** [comment]
just tried again now and made recording 

https://u.pcloud.link/publink/show?code=XZO7rgVZyIQ2uVCgTTpHYIl6UO9xKR9xPKOX

**Comment by inotia00** [comment]
For some reason, it seems that you cannot access APKMirror from the internet you are using.

[YouTube v18.06.41 - APKMirror](http://apkmirror.com/apk/google-inc/youtube/youtube-18-06-41-release/youtube-18-06-41-2-android-apk-download/)

[YouTube v18.06.41 - APKCombo](https://download.apkcombo.com/com.google.android.youtube/YouTube_18.06.41_apkcombo.com.apk?ecp=Y29tLmdvb2dsZS5hbmRyb2lkLnlvdXR1YmUvMTguMDYuNDEvMTUzNjAzNjI4OC5kZDJlMjg2OWRkYjljYzk5YTQyYjQxOTBkNGExYmJkMTYwNGQ2YjNjLmFwaw==&iat=1677168782&sig=00c7a0a5d31e8607c98240bb346a5416&size=131019864)

Download the APK manually, and upload the APK using the upload feature in rvx-builder.
![builder2](https://user-images.githubusercontent.com/108592928/220966235-c387cf95-7da9-44c9-82cd-ce253ca823e1.png)

**Comment by inotia00** [comment]
I checked the video... Unfortunately, there doesn't seem to be any way other than using another method

Use [ReVanced Manager](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)), or use [Revancify](https://github.com/decipher3114/Revancify)

If you are using Revancify, you should change the source to `inotia00`

**Comment by koullis22** [comment]
i tried wifi and data cellular same error. i tried apkmirror from browser and i saw that it uses cloudflare protection maybe thats the problem? 

as for upload function as you can see in video also it redirects at once on "failure" page and when i managed to click it although i had the apk i download folder it wasnt recognized to choose it.

**Comment by inotia00** [comment]
yes.. that is the cause

For some reason, you cannot access APKMirror from your internet network.

Find a VPN that can access APKMirror and use it, or temporarily patch through ReVanced Manager

[ReVanced Manager Guide (for rvx user)](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android))

**Comment by koullis22** [comment]
thanks ill check it out vpn+revancify

as for manager i think i tried it yesterday but i prefer to have it as a 3rd party app instead of replacing original

**Comment by koullis22** [comment]
UPDATE: found it working with proton vpn free
