### ISSUE TITLE
But the YouTube patched has many bugs. I tried compiling with another app (official revanced manager configured to patch from inotia00) and worked perfectly.

### ISSUE THREAD

**Issue by darkvpier** [inotia00/rvx-builder#60]
But the YouTube patched has many bugs. I tried compiling with another app (official revanced manager configured to patch from inotia00) and worked perfectly.

_Originally posted by @darkvpier in https://github.com/inotia00/rvx-builder/issues/56#issuecomment-1441773116_

**Comment by inotia00** [comment]
Please write an issue related to rvx-builder
