### ISSUE TITLE
failure in patching 

### ISSUE THREAD

**Issue by kaiminz** [inotia00/rvx-builder#62]
![Screenshot_20230227-073622](https://user-images.githubusercontent.com/89754237/221454541-68b3715d-4e47-46c2-ae89-6476b4d2f137.jpg)
![Screenshot_20230227-001203](https://user-images.githubusercontent.com/89754237/221454602-ddb3738c-0f6b-4f8c-990f-13878b9e5ef5.jpg)
![Screenshot_20230227-073622](https://user-images.githubusercontent.com/89754237/221454608-d7195d86-2c39-42f6-ab65-a7b0d1af2622.jpg)
**Describe the bug**

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**

**Comment by kaiminz** [comment]
The VPN nodes matter, more often patcher fails. Please fix it.

**Comment by inotia00** [comment]
The internet you are using is not accessing APKMirror
Check your VPN connection
