### ISSUE TITLE
Make Rvx builder Offline

### ISSUE THREAD

**Issue by RabahPrime** [inotia00/rvx-builder#63]
**It is better to add an offline option because the apkmirror site works for me, but the api is not because I always use a VPN**.

![bug](https://user-images.githubusercontent.com/120687572/222072595-1e9ce898-5474-4b28-8a8b-2f678b5f46eb.png)

Windows 11

**Comment by Spacellary** [comment]
Let's watch the changes upstream, reis seems inclined to add this so we're good! :D

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/62
