### ISSUE TITLE
Loading / Buffering Problem 

### ISSUE THREAD

**Issue by Tronak007** [inotia00/rvx-builder#64]
Since Yesterday I'm Facing Problem Any Video I'll Play It Plays For A While Then It Buffers And Never Play Again, This Is Happening With All The Videos, I Tried Reinstall Rebuild And Almost Everything I Thought Any Other Fix Or Trick To Solve The Problem, Please Help

As I Found Out With Me This Happens When I Login To Google Account Through MicroG Without Logging In It Works Fine, Any Fix Or Any Help Anyone Can Provide Please 

Nothing Phone Android 13
Youtube Version Is 18.08.37

**Comment by EnanInoa** [comment]
Same thing here
phone Redmi note 8

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
