### ISSUE TITLE
I'm stuck.

### ISSUE THREAD

**Issue by evd27** [inotia00/rvx-builder#65]
Did the termux thing, got promoted to got to a browser, and the this showed up. Dunno what it means.

https://user-images.githubusercontent.com/87810818/222539330-d5ad1e4a-0207-41e8-9d1e-45fe061a2693.mp4

P.s. pardon me if i didn't comply to rules of submitting an issue (if you had any). wouldn't even know where to look for, let alone follow them.

**Comment by inotia00** [comment]
Some additional libraries of rvx-builder are not completely downloaded

reinstall rvx-builder

Typing the following into termux:
`./rvx-builder.sh reinstall`
