### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by GollumArain** [inotia00/rvx-builder#69]
**The Bug**
 An error occured:
Error: EPERM: operation not permitted, rename './revanced/temp.apk' -> './revanced/com.ss.android.ugc.trill.apk'at renameSync (node:fs:1038:3)at C:\snapshot\rvx-builder2\utils\uploadAPKFile.js:23:11at process.processTicksAndRejections (node:internal/process/task_queues:95:5)Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**To Reproduce**

1. Go to 'Apk Selection'
2. Click on 'Apk upload'
3. Choose 'Local Apk'

**revanced-builder Version:** [ v3.8.0]

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 Pro

**Comment by inotia00** [comment]
rvx-builder only supports YouTube and YouTube Music
Why would you want to patch TikTok?
