### ISSUE TITLE
[rvx-builder v3.4.16] "Error: EBUSY: resource busy or locked" and "Finished downloading files" but no files get downloaded, "revanced" folder is empty... ERROR

### ISSUE THREAD

**Issue by Spacellary** [inotia00/rvx-builder#7]
# Updated: Still getting `Error: EBUSY: resource busy or locked`, also tried doing again from a different folder and I get a `[builder] Finished downloading files.` but no files get downloaded, `revanced` folder is empty... or when it downloads them I get the `Error: EBUSY` when patching...
_Updated title._
Tried ReisXD builder and it is working fine.

#### Full Patching Process:
https://user-images.githubusercontent.com/39604793/198880408-95b6f341-6aec-44a3-9ca4-6758c46e22a3.mp4

```
Error: EBUSY: resource busy or locked, unlink '\\?\D:\Ferramentas\revanced\inotia00-rvx-builder\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
```

**Tried `rvx-builder-v3.4.15` and `rvx-builder-v3.4.16` and same thing happens on both.**
<hr>

## **Describe the bug**
Builder fails to patch, using the versions and rvx-resources bellow:
    revanced-integrations-v0.63.0
    revanced-patches-v2.99.0
    revanced-cli-v2.14.0

## **Steps To Reproduce**

1. Try to build latest recommended (Youtube v17.42.35).
2. Failure.

## **Screenshots**
![msedge_8S7C0AgL7i](https://user-images.githubusercontent.com/39604793/198876817-a3fa13e9-e5b5-4348-8c42-2efa4fdd819c.png)

<hr>

**revanced-builder Version:** rvx-builder v3.4.16

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context: Crash Report**
```
[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\D:\Edge Downloads 2022.4\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
```

```
[builder] An error occured.
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:747:3)
    at Object.readSync (pkg/prelude/bootstrap.js:947:32)
    at tryReadSync (node:fs:447:20)
    at Object.readFileSync (node:fs:493:19)
    at readFileSync (pkg/prelude/bootstrap.js:1082:36)
    at parsePatch (C:\snapshot\rvx-builder-build3\utils\PatchesParser.js:9:5)
    at getPatches (C:\snapshot\rvx-builder-build3\wsEvents\getPatches.js:28:24)
    at WebSocket.<anonymous> (C:\snapshot\rvx-builder-build3\index.js:175:15)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (C:\snapshot\rvx-builder-build3\node_modules\ws\lib\websocket.js:1178:20)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

```

**Comment by Spacellary** [comment]
Could be related to https://github.com/reisxd/revanced-builder/issues/502#issue-1401820035
I'll keep trying what I can

**Comment by Spacellary** [comment]
![image](https://user-images.githubusercontent.com/39604793/198881272-6881f55d-7a70-4136-a876-65a94ca08c50.png)
as expected java.exe is holding that file but I dunno if I can do anything about it when force stop it obv the builder just stops responding :/

**Comment by Dhrubaof2002** [comment]
![Uploading x2{579cf83} (201f6058-c976-42c0-8615-08b85216b415 id=0x7f0a03f6 tag=BaseCommentFragment) …]()

**Comment by inotia00** [comment]
not reproduced at all
However, I can only vaguely guess that it is an issue of java.

If it is true that java is holding the file or directory, try the patch by moving `rvx-builder-win.exe` to another directory.

**Comment by Dhrubaof2002** [comment]
I am getting this error with updated everything an hour ago and trying to patch the latest recommended version.![Screenshot_2022-10-30-19-34-19-422_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/64865031/198882977-80b83311-d1ed-43be-b49e-7e540c45f82b.jpg)

**Comment by Spacellary** [comment]
> not reproduced at all
> However, I can only vaguely guess that it is an issue of java.
> 
> If it is true that java is holding the file or directory, try the patch by moving `rvx-builder-win.exe` to another directory.

Rebooted my PC, moved file to a different directory in a different Disk, from D: to C:, same result.

**Comment by Spacellary** [comment]
@inotia00 
I was able to now build normally after doing the following steps:

    1) Uninstalled the Zulu JDK 17 version that was installed.
    2) Uninstalled Node.js.
    3) Installed Zulu JDK again (Zulu JDK 17 v17.36.15 from Winget).
`[builder] ReVanced has been built! Please transfer over revanced/ReVanced-YouTube-v17.42.35-cli_v2.14.1-patches_v2.99.0.apk and if you are using YT/YTM, revanced/microg.apk and install them!`

**Comment by inotia00** [comment]
> `[builder] ReVanced has been built! Please transfer over revanced/ReVanced-YouTube-v17.42.35-cli_v2.14.1-patches_v2.99.0.apk and if you are using YT/YTM, revanced/microg.apk and install them!`

Thank you so much for sharing the method you solved
If anyone has the same issue, this method will be very helpful for them.

**Comment by Spacellary** [comment]
@meetaditya Added a bit more context to https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651 as it seems to work for other people too, if you would still have the issue, please try again and remove all versions and related files related to Java as mentioned before and hopefully that will do it for you too.

**Comment by meetaditya** [comment]
@Spacellary Thanks for your help!  

"ReVanced has been built! Please transfer over revanced/ReVanced-YouTube-v17.42.35-cli_v2.14.1-patches_v2.99.0.apk and if you are using YT/YTM, revanced/microg.apk and install them!"

Uninstalled everything as you mentioned, I noticed that path variables still had the path set to previous installation folder so I removed that manually and then did a fresh install. That fixed it for me. :)

**Comment by Skrell** [comment]
> 17.36.15

Don't we need Node.js to build?

**Comment by Spacellary** [comment]
Only installing Zulu Open JDK will have everything needed. Not necessary to install Node.js separately.

**Comment by Skrell** [comment]
Well the bad news is it didn't work....but the GOOD news is I got a different error message(s)!

```
[builder] INFO: Signing revanced_aligned.apk to revanced_signed.apk
[builder] Exception in thread "main"
[builder] java.lang.OutOfMemoryError: Unable to allocate 1048576 bytes
[builder] at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unsafe.java:632)
[builder] at java.base/java.nio.DirectByteBuffer.(DirectByteBuffer.java:125) at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332) at com.android.apksig.internal.util.FileChannelDataSource.feed(FileChannelDataSource.java:102) at com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:384) at com.android.apksig.ApkSigner.fulfillInspectInputJarEntryRequest(ApkSigner.java:621) at com.android.apksig.ApkSigner.sign(ApkSigner.java:385) at com.android.apksig.ApkSigner.sign(ApkSigner.java:204) at app.revanced.utils.signing.Signer.signApk(Signer.kt:77) at app.revanced.cli.signing.Signing.sign(Signing.kt:10) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:174) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
[builder] at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

**Comment by Spacellary** [comment]
This is actually good news, I did get that error too after the previous one and eventually it worked out.

Things I tried, If you don't mind or haven't tried already:
Clean uninstall JDK again. Reboot. Install again.
Do a `java --version` in the Terminal, to make sure you got have anything left, and do again to see if everything is installed after you do install again, after the reboot...
Hopefully this helps somehow. I tried many things so can't hurt to try too.

**Comment by Skrell** [comment]
I selected ALL the patches and it worked this time!!!! IT WORKED!!! TYTYTYTYTYTY!!!!

**Comment by limico99** [comment]
I failed on Windows 11 (22621.608.51.6), but after installing zulu19.30.11 in a sandbox environment, I succeeded in patching with rvx-builder v3.4.16.

**Comment by Impulse666** [comment]
For anyone else experiencing similar issues Windows, make sure to uninstall your current Azul Zulu JDK installation and install the last Java 17 (LTS) **x86 32-bit** version from this page: https://www.azul.com/downloads/?version=java-17-lts&os=windows&architecture=x86-32-bit&package=jdk

Note: 64-bit version seems to cause some issues with both rvx-builder from inotia00 and revanced-builder from reixd.

**Comment by inotia00** [comment]
This bug, which I thought would last a forever, is no longer reproduced in the latest release

Unpin the issue

**Comment by Spacellary** [comment]
@inotia00 Gotta love Java on Windows... Glad it seems solved 👏🎉
