### ISSUE TITLE
Rvx builder does not work 

### ISSUE THREAD

**Issue by Pipivi** [inotia00/rvx-builder#71]
![Screenshot_20230314-160007](https://user-images.githubusercontent.com/41041415/225008583-e2adec2f-bf64-4c92-af77-292bf64b86a4.png)
Error presented on the screenshot

**Comment by Pipivi** [comment]
> 

The restart of the script helped. Didn't have to turn off VPN 🤷🏻‍♂️

**Comment by inotia00** [comment]
In my case, adguard vpn blocked apkmirror's api, and the same issue as the attached screenshot was reproduced.

That's why I advise you to turn off vpn
