### ISSUE TITLE
rvx-builder-linux will not work.

### ISSUE THREAD

**Issue by pr3dicament** [inotia00/rvx-builder#72]
I get this in the terminal, as well as the web browser:

./rvx-builder-linux 
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: You got ratelimited from GitHub
...Completely? What did you even do?
    at getDownloadLink (/snapshot/rvx-builder2/utils/FileDownloader.js:52:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadFiles (/snapshot/rvx-builder2/utils/FileDownloader.js:164:26)
    at async updateFiles (/snapshot/rvx-builder2/wsEvents/updateFiles.js:73:3)
    at async WebSocket.<anonymous> (/snapshot/rvx-builder2/index.js:178:9)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

And no, I wasn't connected to a VPN of any kind.  This is just from the ISP.  I'm not very active on here so this really doesn't make sense to me.  I didn't see anything about this and had nowhere else to turn.

After this, if I try again without restarting rvx-builder-linux, it says the following in the browser:

[builder] Downloading process hasn't finished and you tried to download again.

**Comment by pr3dicament** [comment]
Yeah, it's still doing it on 3.9.0.  No change at all.

**Comment by Mahdishahin** [comment]
![IMG_20230429_030639.jpg](https://user-images.githubusercontent.com/62628396/235270004-29d890af-f001-4472-a7ea-4dd3b40cc6e2.jpg)

same problem in android termux

**Comment by inotia00** [comment]
this is outdated issue, I'll closing issue
