### ISSUE TITLE
Could not find instagram downloads

### ISSUE THREAD

**Issue by Lucas559-noob** [inotia00/rvx-builder#74]
**Describe the bug**
Could not get versions of Instagram to download

**To Reproduce**

1. Select instagram
2. Select patches
3. Go for download versions

**Screenshots**
![image](https://user-images.githubusercontent.com/54007604/228411337-67991023-61e6-4113-870d-bb8849202703.png)

**revanced-builder Version:** 3,9

**Desktop (please complete the following information):**

- OS: Windows
- Version: 8.1

**Additional context**

**Comment by inotia00** [comment]
rvx-builder does no support instagram
