### ISSUE TITLE
How to disable predictive back gesture (I think that's what it's called!) 

### ISSUE THREAD

**Issue by lewdpatriot** [inotia00/rvx-builder#75]
When swiping from the top to show notification panel, the gesture to exit full screen mode triggers. How to disable this. 

https://user-images.githubusercontent.com/63286528/228444501-f48c7267-9e22-46df-af56-fc9c4e304274.mp4

**Comment by inotia00** [comment]
you can't disable it
it depends on the system you are using

**Comment by lewdpatriot** [comment]
But the previous built using v3.8.0 works perfectly. Even the normal youtube app. It happens with newer revanced patches and extended v3.9.0.

(I'm on android 11, so it should not be the os🤷🏾‍♂️)
