### ISSUE TITLE
error ??

### ISSUE THREAD

**Issue by qweasdzxc416** [inotia00/rvx-builder#77]
<font class="papago-parent"><font class="papago-source" style="display:none;">![image](https://user-images.githubusercontent.com/55783157/231760575-5d438b89-11c6-4fe2-9010-0072a1c25340.png)</font>![ image ](https://user-images.githubusercontent.com/55783157/231760575-5d438b89-11c6-4fe2-9010-0072a1c25340.png)</font>

windows 11 pro
(korea)

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/7
