### ISSUE TITLE
Can't Select the version of Youtube Music to download

### ISSUE THREAD

**Issue by PenguinSoupX** [inotia00/rvx-builder#80]
**Describe the bug**

In the "Select the version that you want to download" page i am unable to select the version of youtube music that is now recomended ie 5.39.52 as the list ends at version 5.40.52 but i cant go to the second page as the next page button is missing which is present in the reisxd version.

**To Reproduce**

1. Start Patching
2. Click on Youtube Music and confirm patches
3. In the "Select the version that you want to download" page the version number ends at 5.40.52 and next page button is not there

**Screenshots**
![rvx-builder](https://user-images.githubusercontent.com/58871943/234283190-e02f3f41-0de3-4760-9496-1bbe95e19366.png)

**revanced-builder Version:**  3.9.1

**Desktop (please complete the following information):**

- OS: Manjaro Linux x86_64 
- Version: 6.1.25-1-MANJARO 

**Additional context**
reisxd/revanced-builder has the button
![revanced-builder](https://user-images.githubusercontent.com/58871943/234283622-e2c851fe-75b1-4756-b381-216779b44348.png)

**Comment by inotia00** [comment]
Unlike official ReVanced Music, ReVanced Music Extended supports all versions
