### ISSUE TITLE
Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by androidghosh** [inotia00/rvx-builder#82]
**Describe the bug**
The builder is erroring with this, 
`[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
Not sure what to do with typed value of type 0x4, falling back to reading an uint32.
[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\rudra\Downloads\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-main2\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-main2\wsEvents\patchApp.js:186:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
`

**To Reproduce**
run it
select youtube
select all patches
select 18.16.37 apk
after almost complete it gets errored
there was no log.txt file

same thing happens when I manually add the apk instead of downloading from apkmirror
Happens every time. Also happens when not all patches are included.
Looks like a [widespread issue](https://github.com/reisxd/revanced-builder/issues/700)

**Screenshots**
![image](https://user-images.githubusercontent.com/17355109/235418070-fb55990d-e30a-4b36-9481-7555c6f69167.png)

**revanced-builder Version:** 3.9.1

**Desktop (please complete the following information):**

- OS: Win 10 Home latest update 1/05/2023

**Additional context**
Oddly, if I install revanced_signed.apk from revanced-cache folder, everything seems to work. 

Also, I later found this, [these two](https://github.com/inotia00/rvx-builder/issues/7) might be same. I'll try to implement the solutions given there.

**Comment by inotia00** [comment]
If the issue persists despite you following [this guide](https://github.com/inotia00/rvx-builder/issues/7), please follow the method below:

1. Close rvx-builder
2. If you have Zulu in Windows Task Manager, force close it
3. Delete the `revanced-cache` directory
4. Run rvx-builder again, continue patching

**Comment by NeeRaj-2401** [comment]
![image](https://user-images.githubusercontent.com/88180887/235924132-03711e94-e484-45e8-88ab-65a7606d7d27.png)

@inotia00
