### ISSUE TITLE
Error: spawn C:\snapshot\rvx-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT

### ISSUE THREAD

**Issue by mabig9** [inotia00/rvx-builder#84]
**Describe the bug**
As usual, I ran rvx builder I'm using Zulu JDK 17.42.18 32-bit
I reinstalled the Zulu sdk, deleted the revanced-cache and revanced folders and tried the patch again.

**Screenshots**
![image](https://user-images.githubusercontent.com/94786435/235926079-be108d2d-0df0-41f0-8ac1-7fb84c1e755a.png)

**revanced-builder Version:** [3.9.2]

**Desktop (please complete the following information):**

- OS: [Windows 10 Education 22H2]

**Additional context**

**Comment by inotia00** [comment]
Uninstall Zulu JDK 17.42.18 32-bit, install Zulu JDK 17.42.19 64-bit and try again?

**Comment by mabig9** [comment]
![image](https://user-images.githubusercontent.com/94786435/235946202-948e0c2c-6bbf-4861-9e55-19fbb46e9c7b.png)
It works very well! Thank you
I usde Zulu JDK 18.42.19 64-bit
