### ISSUE TITLE
ERROR: spawn ps ENOENT

### ISSUE THREAD

**Issue by seriousfreedom** [inotia00/rvx-builder#85]
**Describe the bug**
im not sure what this is but thought i should report it just the same
**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**
recent:///d58563974fa5c64572fcf8b5645289a4

- OS:ubuntu cinnominrecent:///3ffe71af90531aee2d43da3664528ab7

- Version: [e.g. 10]

**Additional context**

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/84
