### ISSUE TITLE
Rvx failure

### ISSUE THREAD

**Issue by fazilsheik96** [inotia00/rvx-builder#90]
![Screenshot_20230506-025446](https://user-images.githubusercontent.com/84673105/236571501-5f9e17c5-bfb1-48b0-8ef7-f64c3301c631.png)
**Describe the bug**
Ater patching , rvx builder fails unexpectedly please find the attachment 

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/2
