### ISSUE TITLE
Version tags created on wrong branch

### ISSUE THREAD

**Issue by Zoey2936** [inotia00/rvx-builder#91]
**Describe the bug**
Version tags are created on wrong branch

**To Reproduce**

1. Run: `git clone --recursive https://github.com/inotia00/rvx-builder --branch v3.9.2 /src`
2. See it is tagged from the main branch, not the revanced-extended branch

**Comment by inotia00** [comment]
I've never had my default branch set to `revanced-extended` after forking until now.
Because of this, until now, when you typed the command, the source was downloaded from the `main` branch.

Now that I have changed the default branch to `revanced-extended`, this issue should no longer occur.

**Comment by Zoey2936** [comment]
thanks
