### ISSUE TITLE
rvx builder fails

### ISSUE THREAD

**Issue by fazilsheik96** [inotia00/rvx-builder#92]
So builder compiles the needed patch but fails during mounting actually im using kernelSU based root not magisk.

![Screenshot_20230507-005909.png](https://user-images.githubusercontent.com/84673105/236643281-8ebd1a15-49e6-44df-9e48-09a80150986f.png)

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/2
