### ISSUE TITLE
[ANDROID/temux] - Builder fails when trying to patch microG

### ISSUE THREAD

**Issue by r0ckarong** [inotia00/rvx-builder#94]
**Describe the bug**
When trying to patch Vanced microG the builder fails with this error message:

**To Reproduce**
1. Update to rvx-builder 3.9.3
2. Fix npm errors with `npm audit fix`
3. Run builder
4. Select microG from apps to patch
5. Select patches
6. By this time it will already have crashed without clicking anything else

**Screenshots**
![Screenshot_20230711_145322_Firefox](https://github.com/inotia00/rvx-builder/assets/4920542/114bb495-7a4c-47e6-8589-dcfdbc1f47e7)
![Screenshot_20230711_145335_Termux](https://github.com/inotia00/rvx-builder/assets/4920542/2844aaa5-c4f7-44ad-ae02-4554da259f6a)

**revanced-builder Version:**
3.9.3

**Desktop (please complete the following information):**
Samsung Galaxy S10, Android 12, temux 0.118.9, npm 9.8.0

**Comment by inotia00** [comment]
ah, rvx-builder v3.9.3 will be compatible starting with revanced-patches-v2.184.1

There are many things to release today, so rvx-builder was released first

Please test again after revanced-patches-v2.184.1 is released in a while

**Comment by inotia00** [comment]
seems to be fixed

**Comment by r0ckarong** [comment]
I've just reinstalled rvx-builder to 3.9.4 and I'm seeing the same message.
revanced-patches is 2.184.3
I select the "Hide from launcher" patch and Click continue. It goes to the "Select the version you want to download" screen and there it crashes automatically without me doing anything.

**Comment by inotia00** [comment]
ah, you have to manually download the MicroG APK and upload it via the `Upload APK` button

There are two types of MicroG that can be patched.
https://github.com/inotia00/VancedMicroG/releases
https://github.com/inotia00/mMicroG/releases

If you just click the Next button without uploading an APK, rvx-builder will try to download the old Vanced MicroG from APKMirror.
rvx-builder prints an error in this case

**Comment by r0ckarong** [comment]
> If you just click the Next button without uploading an APK, rvx-builder will try to download the old Vanced MicroG from APKMirror.
> rvx-builder prints an error in this case

Wouldn't it make sense to catch that error and tell this to the user? I had no idea.

**Comment by inotia00** [comment]
sure I'll handle this exception later when I have time

**Comment by r0ckarong** [comment]
> sure I'll handle this exception later when I have time

Much appreciated, like the rest of all the great work you're doing. Thanks.
