### ISSUE TITLE
v8a only build

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/rvx-builder#95]
I have no way to contact you, so I'm leaving it here.  Unlike the youtube music apk, the youtube apk distributed by https://revancedextended.com/en/ does not have a v8a-only build.  I can't build it separately, so if possible, I would sincerely appreciate it if you could upload the youtube apk as a v8a-only build.  please.

**Comment by inotia00** [comment]
That website is fake
I do not distribute prebuilt APK
