### ISSUE TITLE
Non Root version not flash with magisk

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/rvx-builder#97]
I duild 2 YouTube revance non root & root version. Non Root version property working but root version not working.. Root version not flash with magisk 
![Screenshot_2023-07-18-02-46-02-762_com topjohnwu magisk](https://github.com/inotia00/rvx-builder/assets/117540245/5269c4cb-35d1-405f-b64e-1fcbf9a1ed61)
![Screenshot_2023-07-18-02-42-17-834_app revanced manager flutter](https://github.com/inotia00/rvx-builder/assets/117540245/b08bee5f-a89b-49a6-a5ef-804fa55bca8c)

**Comment by inotia00** [comment]
Wrong place to report issues
