### ISSUE TITLE
rvx-builder target archtecture setup

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/rvx-builder#98]
1. Can't I specify the target architecture when building on a mobile phone using rvx-builder? (ex. arm64-v8a only) 

2. Is it not possible to re-patch a new version patch of an apk that has already been patched?

**Comment by inotia00** [comment]
1. Only through CLI commands. rvx-builder also uses CLI, but no such command is included
2. Instead of using the patched APK when redeploying, you must use the YouTube APK
If it's already downloaded to your device (YouTube APK), you can just use it
